#!/bin/bash -ex

dl() {
    [ "$FAB_HTTP_PROXY" ] && PROXY="--proxy $FAB_HTTP_PROXY"
    cd $2; curl -L -f -O $PROXY $1; cd -
}

URL='https://www.concretecms.com/application/files/7116/8918/7686/concrete-cms-9.2.1.zip'
dl $URL /usr/local/src
