#!/bin/bash -ex

DB_NAME=concrete
DB_USER=concrete
DB_PASS=$(mcookie)

ADMIN_PASS=turnkey1
ADMIN_MAIL=admin@example.com

SRC=/usr/local/src
WEBROOT=/var/www/concrete
# shellcheck disable=SC1091
. "$SRC/concrete-cms-release"
ARCHIVE="$SRC/concrete-cms-$CONCRETE_CMS_VERSION.zip"

mkdir -p "$WEBROOT"
cd "$(dirname "$WEBROOT")"

unzip "$ARCHIVE"
rm -f "$ARCHIVE"
mv "concrete-cms-$CONCRETE_CMS_VERSION" concrete/public
chmod 0755 "$WEBROOT/public/concrete/bin/concrete"
install -D -m 0644 "$SRC/concrete-cms-release" \
    /usr/local/share/concrete-cms-release
rm -f "$SRC/concrete-cms-release"

# configure apache
a2dissite 000-default
a2ensite concrete
a2enmod rewrite

# start services
service mariadb start
service apache2 start

# setup the database
mariadb --batch --execute "CREATE DATABASE $DB_NAME CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;"
mariadb --batch --execute "CREATE USER '$DB_USER'@'localhost' IDENTIFIED BY '$DB_PASS';"
mariadb --batch --execute "GRANT ALL PRIVILEGES ON $DB_NAME.* TO '$DB_USER'@'localhost'; FLUSH PRIVILEGES;"

chown -R www-data:www-data "$WEBROOT"

turnkey-concrete c5:install \
    --db-server=localhost --db-username="$DB_USER" --db-password="$DB_PASS" \
    --db-database="$DB_NAME" --site=TurnKey-Concrete-CMS \
    --starting-point=elemental_full --admin-email="$ADMIN_MAIL" \
    --admin-password="$ADMIN_PASS"

cat >"$WEBROOT/public/.htaccess" <<EOF
<IfModule mod_rewrite.c>
    RewriteEngine On
    RewriteBase /
    RewriteCond %{REQUEST_FILENAME} !-f
    RewriteCond %{REQUEST_FILENAME}/index.html !-f
    RewriteCond %{REQUEST_FILENAME}/index.php !-f
    RewriteRule . index.php [L]
</IfModule>
EOF

rm -rf "$WEBROOT/public/application/files/cache/"*

# stop services
service mariadb stop
service apache2 stop
