#!/bin/sh -ex

DB_NAME=concrete5
DB_USER=concrete5
DB_PASS=$(mcookie)

ADMIN_NAME=admin
ADMIN_PASS=turnkey
ADMIN_MAIL=admin@example.com

SRC=/usr/local/src
WEBROOT=/var/www/concrete5

# unpack and configure permissions
unzip $SRC/concrete5.zip -d $(dirname $WEBROOT)
mv $(dirname $WEBROOT)/concrete5.* $WEBROOT
rm $SRC/concrete5.zip
chown -R root:root $WEBROOT
chown -R www-data:www-data $WEBROOT/application/files
chown -R www-data:www-data $WEBROOT/application/config
chown -R www-data:www-data $WEBROOT/packages

# configure apache
a2dissite default
a2ensite concrete5
a2enmod rewrite

# start services
/etc/init.d/mysql start
/etc/init.d/apache2 start

# setup the database
MYSQL_BATCH="mysql --user=root --password=$MYSQL_PASS --batch"
MYSQL_ADMIN="mysqladmin --user=root --password=$MYSQL_PASS"

$MYSQL_ADMIN create $DB_NAME
$MYSQL_BATCH --execute "grant all privileges on $DB_NAME.* to $DB_USER@localhost identified by '$DB_PASS'; flush privileges;"

# curl based install
EMAIL=$(echo $ADMIN_MAIL | sed s/@/%40/)
URL="http://127.0.0.1/index.php/install/"
CURL="curl -c /tmp/cookie -b /tmp/cookie"

$CURL ${URL}setup/ --data "locale=en_US"
$CURL ${URL}configure/ --data "locale=en_US&SITE=TurnKey+Concrete5&uEmail=$EMAIL&uPassword=$ADMIN_PASS&uPasswordConfirm=$ADMIN_PASS&DB_SERVER=localhost&DB_USERNAME=$DB_USER&DB_PASSWORD=$DB_PASS&DB_DATABASE=$DB_NAME&SAMPLE_CONTENT=elemental_full"

$CURL ${URL}run_routine/elemental_full/make_directories
$CURL ${URL}run_routine/elemental_full/install_database/
$CURL ${URL}run_routine/elemental_full/add_users/
$CURL ${URL}run_routine/elemental_full/install_permissions/
$CURL ${URL}run_routine/elemental_full/add_home_page/
$CURL ${URL}run_routine/elemental_full/install_attributes/
$CURL ${URL}run_routine/elemental_full/install_blocktypes/
$CURL ${URL}run_routine/elemental_full/install_gathering/
$CURL ${URL}run_routine/elemental_full/install_page_types/
$CURL ${URL}run_routine/elemental_full/install_themes/
$CURL ${URL}run_routine/elemental_full/install_jobs/
$CURL ${URL}run_routine/elemental_full/install_dashboard/
$CURL ${URL}run_routine/elemental_full/install_required_single_pages/
$CURL ${URL}run_routine/elemental_full/install_image_editor/
$CURL ${URL}run_routine/elemental_full/install_config/
$CURL ${URL}run_routine/elemental_full/import_files/
$CURL ${URL}run_routine/elemental_full/install_content/
$CURL ${URL}run_routine/elemental_full/set_site_permissions/
#$CURL ${URL}run_routine/elemental_full/precache/
$CURL ${URL}run_routine/elemental_full/finish/

rm -f /tmp/cookie

# configure pretty urls
#$MYSQL_BATCH --database=$DB_NAME --execute "INSERT INTO Config VALUES ('URL_REWRITING', '2012-05-30 08:17:32', '1', '0', '0');"

cat >$WEBROOT/.htaccess<<EOF
<IfModule mod_rewrite.c>
RewriteEngine On
RewriteBase /
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME}/index.html !-f
RewriteCond %{REQUEST_FILENAME}/index.php !-f
RewriteRule . index.php [L]
</IfModule>
EOF

rm -rf $WEBROOT/application/files/cache/*

# tweak permissions
#chmod 640 $WEBROOT/application/config/site.php

# stop services
/etc/init.d/mysql stop
/etc/init.d/apache2 stop

