#!/bin/bash -e
# regenerate concrete secrets and mysql password

. /etc/default/inithooks

CONF=/var/www/concrete/public/application/config/database.php

PASSWORD=$(mcookie)
sed -i "s|'password' =>.*|'password' => '$PASSWORD',|" $CONF
$INITHOOKS_PATH/bin/mysqlconf.py --user=concrete --pass="$PASSWORD"

