#!/bin/bash -e
# regenerate concrete5 secrets and mysql password

. /etc/default/inithooks

CONF=/var/www/concrete5/application/config/database.php

PASSWORD=$(mcookie)
sed -i "s|'password' =>.*|'password' => '$PASSWORD',|" $CONF
$INITHOOKS_PATH/bin/mysqlconf.py --user=concrete5 --pass="$PASSWORD"

