#!/bin/bash -e
# regenerate concrete5 secrets and mysql password

. /etc/default/inithooks

CONF=/var/www/concrete5/config/site.php

SALT=$(mcookie)$(mcookie)
sed -i "s|PASSWORD_SALT.*|PASSWORD_SALT', '$SALT');|" $CONF

PASSWORD=$(mcookie)
sed -i "s|DB_PASSWORD.*|DB_PASSWORD', '$PASSWORD');|" $CONF
$INITHOOKS_PATH/bin/mysqlconf.py --user=concrete5 --pass="$PASSWORD"

